# Generated by Django 3.2.12 on 2023-06-07 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('talentsport_app', '0002_auto_20230607_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='update_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Date mise à jour'),
        ),
    ]
