# Generated by Django 4.2.3 on 2023-07-12 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('talentsport_app', '0003_alter_posts_update_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='club_history',
            field=models.TextField(blank=True, null=True, verbose_name='Historique de club'),
        ),
        migrations.AddField(
            model_name='user',
            name='current_club',
            field=models.TextField(blank=True, null=True, verbose_name='Club Actuel'),
        ),
        migrations.AddField(
            model_name='user',
            name='discipline_sportive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentsport_app.disciplinesportive', verbose_name='Discipline Sportive'),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.CharField(default=1, max_length=20, verbose_name='Taille'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(choices=[('DEBUTANT', 'Débutant'), ('INTERMEDIAIRE', 'Intermédiaire'), ('PASSIONNER', 'Passioner'), ('PROFESSIONNEL', 'Professionnel')], default=1, max_length=15, verbose_name='Niveau'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='profil_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profil_pic%Y/%m/%d', verbose_name='Profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('F', 'Féminin'), ('M', 'Masculin')], default=1, max_length=15, verbose_name='Sexe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='strong_foot',
            field=models.CharField(choices=[('GAUCHE', 'Gauche'), ('DROIT', 'Droit')], default=1, max_length=15, verbose_name='Pied Fort'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='weight',
            field=models.CharField(default=1, max_length=20, verbose_name='Poids'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(default=1, max_length=30, verbose_name='Ville'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Prénom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Nom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1, max_length=30, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PlayerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('discipline_sportive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentsport_app.disciplinesportive', verbose_name='Discipline Sportive')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='talentsport_app.playerposition', verbose_name='Poste'),
        ),
    ]
