# Generated by Django 4.2.3 on 2023-09-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentsport_app', '0007_user_country_alter_user_adress_alter_user_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin')], max_length=15, null=True, verbose_name='Sexe'),
        ),
    ]
