# Generated by Django 4.2.3 on 2023-09-21 12:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talentsport_app', '0009_comment_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='Abonnés', to=settings.AUTH_USER_MODEL),
        ),
    ]
